"""
/////////////
/// PATHS ///
/////////////
"""

EQUIPMENT_PATH = "data/equipment/"
ENEMIES_PATH = "data/enemies/"
SKILLS_PATH = "data/skills/"

"""
//////////////////
/// NARUTO RPG ///
//////////////////
"""

CLANS = ["Nenhum", "Uchiha", "Senju", "Hyuuga", "Uzumaki", "Nara", "Inuzuka", "Aburame"]

ELEMENTS = ["Nenhum", "Katon", "Suiton", "Doton", "Fuuton", "Raiton"]

NINJA_RANKS = ["Estudante da Academia", "Genin", "Chunin", "Jonin", "ANBU", "Kage"]

MISSION_RANKS = ["D", "C", "B", "A", "S"]

SKILL_TYPE_NINJUTSU = "Ninjutsu"
SKILL_TYPE_TAIJUTSU = "Taijutsu"
SKILL_TYPE_GENJUTSU = "Genjutsu"
SKILL_TYPES = [SKILL_TYPE_NINJUTSU, SKILL_TYPE_TAIJUTSU, SKILL_TYPE_GENJUTSU]

# Suiton > Katon > Fuuton > Raiton > Doton > Suiton
ELEMENT_BEATS = {
    "Suiton": "Katon",
    "Katon": "Fuuton",
    "Fuuton": "Raiton",
    "Raiton": "Doton",
    "Doton": "Suiton",
}

LEGACY_SKILL_FILES = [
    "warrior.json", "mage.json", "cleric.json", "rogue.json", "hunter.json",
    "warlock.json", "gladiator.json",
]

RANK_INDEX = {rank: idx for idx, rank in enumerate(NINJA_RANKS)}

RANK_PROMOTION_REQUIREMENTS = {
    "Genin": {"min_level": 10},
    "Chunin": {"min_level": 30, "missions": {"C": 10}},
    "Jonin": {"min_level": 60, "missions": {"B": 10, "A": 5}},
}

"""
/////////////
/// STATS ///
/////////////
"""

MAXHP_STATKEY = 'MAXHP'
HP_STATKEY = 'HP'
MAXCHAKRA_STATKEY = 'MAXCHAKRA'
CHAKRA_STATKEY = 'CHAKRA'
MAXSTAMINA_STATKEY = 'MAXSTAMINA'
STAMINA_STATKEY = 'STAMINA'
ATK_STATKEY = 'ATK'
DEF_STATKEY = 'DEF'
NINJUTSU_STATKEY = 'NINJ'
MDEF_STATKEY = 'MDEF'
SPEED_STATKEY = 'SPEED'
CRITCH_STATKEY = 'CRITCH'
CRITDMG_STATKEY = 'CRITDMG'

INITIAL_STATS = {
    MAXHP_STATKEY: 25,
    HP_STATKEY: 25,
    MAXCHAKRA_STATKEY: 10,
    CHAKRA_STATKEY: 10,
    MAXSTAMINA_STATKEY: 100,
    STAMINA_STATKEY: 100,
    ATK_STATKEY: 10,
    DEF_STATKEY: 10,
    NINJUTSU_STATKEY: 10,
    MDEF_STATKEY: 10,
    SPEED_STATKEY: 10,
    CRITCH_STATKEY: 10,
    CRITDMG_STATKEY: 10,
}

STATKEYS = [
    MAXHP_STATKEY, HP_STATKEY, MAXCHAKRA_STATKEY, CHAKRA_STATKEY,
    MAXSTAMINA_STATKEY, STAMINA_STATKEY, ATK_STATKEY, DEF_STATKEY,
    NINJUTSU_STATKEY, MDEF_STATKEY, SPEED_STATKEY, CRITCH_STATKEY, CRITDMG_STATKEY,
]

STATKEYS_NO_RESOURCES = [
    ATK_STATKEY, DEF_STATKEY, NINJUTSU_STATKEY, MDEF_STATKEY,
    SPEED_STATKEY, CRITCH_STATKEY, CRITDMG_STATKEY,
]

STATS_NOT_COPYING_AFTER_BATTLE = [
    MAXHP_STATKEY, MAXCHAKRA_STATKEY, MAXSTAMINA_STATKEY,
    HP_STATKEY, CHAKRA_STATKEY, STAMINA_STATKEY,
]

"""
/////////////
/// ITEMS ///
/////////////
"""

HEADBAND_KEY = 'HEADBAND'
ARMOR_KEY = 'ARMOR'
WEAPON_KEY = 'WEAPON'
TOOL_KEY = 'TOOL'

EQUIPMENT_TYPES = [HEADBAND_KEY, ARMOR_KEY, WEAPON_KEY, TOOL_KEY]
HEADBAND_TYPES = ["HEADBAND", "MASK"]
ARMOR_TYPES = ["FLAK_JACKET", "ANBU_ARMOR", "ROBE"]
WEAPON_TYPES = ["KUNAI", "SHURIKEN", "KATANA", "STAFF", "FAN", "CLAWS"]
TOOL_TYPES = ["SCROLL", "PILL", "SEAL"]

INITIAL_EQUIPMENT = {equipment: None for equipment in EQUIPMENT_TYPES}

"""
///////////////
/// OPTIONS ///
///////////////
"""

FULLY_RECOVER_WHEN_LEVELING_UP = True
STAT_UPGRADE_WHEN_LEVELING_UP = 1
STATS_NOT_UPGRADING_WHEN_LEVELING_UP = [CRITCH_STATKEY, CRITDMG_STATKEY]
NORMAL_ATTACK_OPTION = "NORMAL_ATTACK"
SKILL_OPTION = "SKILL"
POSSIBLE_PLAYER_ACTIONS = [NORMAL_ATTACK_OPTION, SKILL_OPTION]
POSSIBLE_ENEMY_ACTIONS = [NORMAL_ATTACK_OPTION, SKILL_OPTION]
LEECH_AMOUNT = 0.5
MAX_INVENTORY_SLOTS = 25
NINJUTSU_DAMAGE_BONUS = 1.20
ENEMY_AI_WEIGHTS = [1, 3]
RAINBOW_ELEMENTAL_ATTACK = "RAINBOW"
WEAKNESS_DAMAGE_BONUS = 1.25
RESISTANCE_DAMAGE_REDUCTION = 0.75
ELEMENTAL_ADVANTAGE_BONUS = 1.25
ELEMENTAL_DISADVANTAGE_REDUCTION = 0.75
TREASURE_CHANCE_WHEN_FIGHTING = 10
NUMBER_OF_ITEMS_IN_TREASURE = 1
KEY_ITEM_DROP_CHANCE = 5
KEY_ITEMS = ["Olho de Sharingan", "Papiro"]

"""
//////////////
/// SKILLS ///
//////////////
"""

SKILL_TAG_STANCE = "STANCE"
SKILL_TAG_DOES_NOT_SKIP_TURN = "DOES_NOT_SKIP_TURN"
SKILL_TAG_LEECH = "LEECH"
SKILL_TAG_SELF_INFLICT_BUFF_DEBUFF = "SELF_INFLICT_BUFF_DEBUFF"
SKILL_TAG_INFLICT_BUFF_DEBUFF = "INFLICT_BUFF_DEBUFF"
SKILL_TAG_ALTERATION = "ALTERATION"
SKILL_TAG_HEALING = "HEALING"
SKILL_TAG_RECOVER_CHAKRA = "RECOVER_CHAKRA"
SKILL_TAG_SHIELD = "SHIELD"
SKILL_TAG_RAINBOW = "RAINBOW"
SKILL_TAG_SELF_REMOVE_DEBUFFS = "SELF_REMOVE_DEBUFFS"
SKILL_TAG_REMOVE_DEBUFFS = "REMOVE_DEBUFFS"
SKILL_TAG_REMOVE_BUFFS = "REMOVE_BUFFS"
SKILL_TAG_DEBUFF_EXPLOIT = "DEBUFF_EXPLOIT"
SKILL_TAG_PARALYSIS = "PARALYSIS"
SKILL_TAG_CONFUSION = "CONFUSION"

"""
/////////////////////
/// BUFFS/DEBUFFS ///
/////////////////////
"""

BUFF_ATK_UP = "ATK_UP"
BUFF_DEF_UP = "DEF_UP"
BUFF_NINJ_UP = "NINJ_UP"
BUFF_MDEF_UP = "MDEF_UP"
BUFF_LUK_UP = "LUK_UP"

DEBUFF_ATK_DOWN = "ATK_DOWN"
DEBUFF_DEF_DOWN = "DEF_DOWN"
DEBUFF_NINJ_DOWN = "NINJ_DOWN"
DEBUFF_MDEF_DOWN = "MDEF_DOWN"
DEBUFF_LUK_DOWN = "LUK_DOWN"
DEBUFF_PARALYSIS = "PARALYSIS"
DEBUFF_CONFUSION = "CONFUSION"

ATK_BD = [BUFF_ATK_UP, DEBUFF_ATK_DOWN]
DEF_BD = [BUFF_DEF_UP, DEBUFF_DEF_DOWN]
NINJ_BD = [BUFF_NINJ_UP, DEBUFF_NINJ_DOWN]
MDEF_BD = [BUFF_MDEF_UP, DEBUFF_MDEF_DOWN]
LUK_BD = [BUFF_LUK_UP, DEBUFF_LUK_DOWN]

BUFFS = [BUFF_ATK_UP, BUFF_DEF_UP, BUFF_NINJ_UP, BUFF_MDEF_UP, BUFF_LUK_UP]
DEBUFFS = [
    DEBUFF_ATK_DOWN, DEBUFF_DEF_DOWN, DEBUFF_NINJ_DOWN, DEBUFF_MDEF_DOWN,
    DEBUFF_LUK_DOWN, DEBUFF_PARALYSIS, DEBUFF_CONFUSION,
]

BUFF_DEBUFF_CONTRARIES = {
    BUFF_ATK_UP: DEBUFF_ATK_DOWN,
    BUFF_DEF_UP: DEBUFF_DEF_DOWN,
    BUFF_NINJ_UP: DEBUFF_NINJ_DOWN,
    BUFF_MDEF_UP: DEBUFF_MDEF_DOWN,
    BUFF_LUK_UP: DEBUFF_LUK_DOWN,
    DEBUFF_ATK_DOWN: BUFF_ATK_UP,
    DEBUFF_DEF_DOWN: BUFF_DEF_UP,
    DEBUFF_NINJ_DOWN: BUFF_NINJ_UP,
    DEBUFF_MDEF_DOWN: BUFF_MDEF_UP,
    DEBUFF_LUK_DOWN: BUFF_LUK_UP,
}

BUFF_DEBUFF_DURATION = 4
GENJUTSU_DEBUFF_DURATION = 3

BUFF_MULTIPLIER = 1.35
DEBUFF_MULTIPLIER = 0.65

BUFF_DEBUFF_TO_MESSAGE = {
    BUFF_ATK_UP: "Taijutsu increased",
    BUFF_DEF_UP: "Defense increased",
    BUFF_NINJ_UP: "Ninjutsu increased",
    BUFF_MDEF_UP: "Genjutsu resistance increased",
    BUFF_LUK_UP: "Luck increased",
    DEBUFF_ATK_DOWN: "Taijutsu decreased",
    DEBUFF_DEF_DOWN: "Defense decreased",
    DEBUFF_NINJ_DOWN: "Ninjutsu decreased",
    DEBUFF_MDEF_DOWN: "Genjutsu resistance decreased",
    DEBUFF_LUK_DOWN: "Luck decreased",
    DEBUFF_PARALYSIS: "Paralyzed",
    DEBUFF_CONFUSION: "Confused",
}

"""
////////////
/// JSON ///
////////////
"""

AREAS_KEYS = ["NAME", "NUMBER", "ENEMY_LIST", "BOSS", "DUNGEONS", "TREASURES", "MIN_RANK"]
DUNGEON_KEYS = ["DUNGEON_NAME", "RECOMMENDED_LVL", "MIN_RANK", "ENEMY_LIST", "BOSS", "ENEMY_COUNT", "LOOT_POOL", "RYO_REWARD"]
ENEMY_KEYS = [
    "NAME", "STATS", "DESCRIPTION", "XP_REWARD", "RYO_REWARD", "POSSIBLE_LOOT",
    "LOOT_CHANCE", "SKILLS", "WEAKNESSES", "RESISTANCES", "IMAGE_URL", "IS_BOSS", "ELEMENT",
]
EQUIPMENT_KEYS = [
    "NAME", "DESCRIPTION", "INDIV_VALUE", "OBJECT_TYPE", "EQUIPMENT_TYPE",
    "STAT_CHANGE_LIST", "NINJUTSU_MULT", "TAIJUTSU_MULT", "CHAKRA_REDUCTION",
]
ITEM_KEYS = ["NAME", "DESCRIPTION", "INDIV_VALUE", "OBJECT_TYPE"]
SHOP_KEYS = ["AREA_NUMBER", "ITEM_LIST"]
SKILL_KEYS = [
    "NAME", "DESCRIPTION", "CHAKRA_COST", "STAMINA_COST", "POWER", "ELEMENT",
    "COOLDOWN", "TAGS", "PERCENTAGE_COST", "SKILL_TYPE",
]
BLESSING_KEYS = ["NAME", "STAT_CHANGE_LIST", "ESSENCE_COST"]
MISSION_KEYS = ["NAME", "DESCRIPTION", "RANK", "RANK_REQUIRED", "STAMINA_COST", "XP_REWARD", "RYO_REWARD", "DURATION"]
